//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSurveyApp.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleSurveyApp.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        public static string CurrQCodeDescQ1 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        public static string CurrQCodeDescQ2 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3.
        /// </summary>
        public static string CurrQCodeDescQ3 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string LeftBtnLblPrev {
            get {
                return ResourceManager.GetString("LeftBtnLblPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all that apply. (multiple answers).
        /// </summary>
        public static string MainInstructionLblMultipleAnswers {
            get {
                return ResourceManager.GetString("MainInstructionLblMultipleAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have finished your review, click here..
        /// </summary>
        public static string MainInstructionLblReview {
            get {
                return ResourceManager.GetString("MainInstructionLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option. (single answer).
        /// </summary>
        public static string MainInstructionLblSingleAnswer {
            get {
                return ResourceManager.GetString("MainInstructionLblSingleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review your answers here..
        /// </summary>
        public static string MainQuestionLblReview {
            get {
                return ResourceManager.GetString("MainQuestionLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 1: Single Answer.
        /// </summary>
        public static string QTextQ1 {
            get {
                return ResourceManager.GetString("QTextQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 2: Single Answer.
        /// </summary>
        public static string QTextQ2 {
            get {
                return ResourceManager.GetString("QTextQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 3: Single Answer.
        /// </summary>
        public static string QTextQ3 {
            get {
                return ResourceManager.GetString("QTextQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string RightBtnLblNext {
            get {
                return ResourceManager.GetString("RightBtnLblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string RightBtnLblReview {
            get {
                return ResourceManager.GetString("RightBtnLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Survey.
        /// </summary>
        public static string SaveSurveyBtnLbl {
            get {
                return ResourceManager.GetString("SaveSurveyBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Survey.
        /// </summary>
        public static string ScreenNameLblEndOfSurvey {
            get {
                return ResourceManager.GetString("ScreenNameLblEndOfSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ScreenNameLblReview {
            get {
                return ResourceManager.GetString("ScreenNameLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Survey App.
        /// </summary>
        public static string ScreenNameLblStart {
            get {
                return ResourceManager.GetString("ScreenNameLblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Survey.
        /// </summary>
        public static string StartSurveyLbl {
            get {
                return ResourceManager.GetString("StartSurveyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum character allowed is.
        /// </summary>
        public static string TextInstructionLbl {
            get {
                return ResourceManager.GetString("TextInstructionLbl", resourceCulture);
            }
        }
    }
}
