//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSurveyApp.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleSurveyApp.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode01ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode01ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode01ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode01ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode02ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode02ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (goes to Review).
        /// </summary>
        public static string CurrQCode02ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode02ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode03ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode03ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (Goes to Text).
        /// </summary>
        public static string CurrQCode03ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode03ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Selection Option 1.
        /// </summary>
        public static string CurrQCode04ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode04ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Selection Option 2 (Goes to Review).
        /// </summary>
        public static string CurrQCode04ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode04ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 12.
        /// </summary>
        public static string CurrQCode05ACode012AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode012AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 1.
        /// </summary>
        public static string CurrQCode05ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 2.
        /// </summary>
        public static string CurrQCode05ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 3.
        /// </summary>
        public static string CurrQCode05ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 4.
        /// </summary>
        public static string CurrQCode05ACode04AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode04AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 5.
        /// </summary>
        public static string CurrQCode05ACode05AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode05AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 6.
        /// </summary>
        public static string CurrQCode05ACode06AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode06AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 7.
        /// </summary>
        public static string CurrQCode05ACode07AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode07AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 8.
        /// </summary>
        public static string CurrQCode05ACode08AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode08AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 9.
        /// </summary>
        public static string CurrQCode05ACode09AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode09AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 10.
        /// </summary>
        public static string CurrQCode05ACode10AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode10AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 11.
        /// </summary>
        public static string CurrQCode05ACode11AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode11AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 13.
        /// </summary>
        public static string CurrQCode05ACode13AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode13AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 14.
        /// </summary>
        public static string CurrQCode05ACode14AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode14AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 15.
        /// </summary>
        public static string CurrQCode05ACode15AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode15AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 16.
        /// </summary>
        public static string CurrQCode05ACode16AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode16AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 17.
        /// </summary>
        public static string CurrQCode05ACode17AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode17AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection Option 18.
        /// </summary>
        public static string CurrQCode05ACode18AText {
            get {
                return ResourceManager.GetString("CurrQCode05ACode18AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CurrQCode06ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode06ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A little.
        /// </summary>
        public static string CurrQCode06ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode06ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some.
        /// </summary>
        public static string CurrQCode06ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode06ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lot.
        /// </summary>
        public static string CurrQCode06ACode04AText {
            get {
                return ResourceManager.GetString("CurrQCode06ACode04AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode06ACode05AText {
            get {
                return ResourceManager.GetString("CurrQCode06ACode05AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode07ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode07ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode07ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode07ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode07ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode07ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode08ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode08ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode08ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode08ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode08ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode08ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode09ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode09ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode09ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode09ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode09ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode09ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode10ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode10ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode10ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode10ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode10ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode10ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode11ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode11ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode11ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode11ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode11ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode11ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CurrQCode12ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode12ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CurrQCode12ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode12ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not observe.
        /// </summary>
        public static string CurrQCode12ACode03AText {
            get {
                return ResourceManager.GetString("CurrQCode12ACode03AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string CurrQCode13ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode13ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string CurrQCode13ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode13ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CurrQCode14ACode01AText {
            get {
                return ResourceManager.GetString("CurrQCode14ACode01AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CurrQCode15ACode02AText {
            get {
                return ResourceManager.GetString("CurrQCode15ACode02AText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        public static string CurrQCodeDescQ1 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        public static string CurrQCodeDescQ2 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3.
        /// </summary>
        public static string CurrQCodeDescQ3 {
            get {
                return ResourceManager.GetString("CurrQCodeDescQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string LeftBtnLblPrev {
            get {
                return ResourceManager.GetString("LeftBtnLblPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all that apply. (multiple answers).
        /// </summary>
        public static string MainInstructionLblMultipleAnswers {
            get {
                return ResourceManager.GetString("MainInstructionLblMultipleAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have finished your review, click here..
        /// </summary>
        public static string MainInstructionLblReview {
            get {
                return ResourceManager.GetString("MainInstructionLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option. (single answer).
        /// </summary>
        public static string MainInstructionLblSingleAnswer {
            get {
                return ResourceManager.GetString("MainInstructionLblSingleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review your answers here..
        /// </summary>
        public static string MainQuestionLblReview {
            get {
                return ResourceManager.GetString("MainQuestionLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q01.
        /// </summary>
        public static string Q01CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q01CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 01: Single Answer.
        /// </summary>
        public static string Q01QText {
            get {
                return ResourceManager.GetString("Q01QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q02.
        /// </summary>
        public static string Q02CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q02CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 02: Single Answer.
        /// </summary>
        public static string Q02QText {
            get {
                return ResourceManager.GetString("Q02QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q03.
        /// </summary>
        public static string Q03CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q03CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 03: Single Answer.
        /// </summary>
        public static string Q03QText {
            get {
                return ResourceManager.GetString("Q03QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q04.
        /// </summary>
        public static string Q04CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q04CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 04: Single Answer.
        /// </summary>
        public static string Q04QText {
            get {
                return ResourceManager.GetString("Q04QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q05.
        /// </summary>
        public static string Q05CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q05CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 05: Multiple Answers.
        /// </summary>
        public static string Q05QText {
            get {
                return ResourceManager.GetString("Q05QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q06.
        /// </summary>
        public static string Q06CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q06CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 06: Single Answer.
        /// </summary>
        public static string Q06QText {
            get {
                return ResourceManager.GetString("Q06QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q07.
        /// </summary>
        public static string Q07CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q07CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 07: Single Answer.
        /// </summary>
        public static string Q07QText {
            get {
                return ResourceManager.GetString("Q07QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q08.
        /// </summary>
        public static string Q08CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q08CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 08 : Single Answer.
        /// </summary>
        public static string Q08QText {
            get {
                return ResourceManager.GetString("Q08QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q09.
        /// </summary>
        public static string Q09CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q09CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 09: Single Answer.
        /// </summary>
        public static string Q09QText {
            get {
                return ResourceManager.GetString("Q09QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q10.
        /// </summary>
        public static string Q10CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q10CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 10: Single Answer.
        /// </summary>
        public static string Q10QText {
            get {
                return ResourceManager.GetString("Q10QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q11.
        /// </summary>
        public static string Q11CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q11CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 11: Single Answer.
        /// </summary>
        public static string Q11QText {
            get {
                return ResourceManager.GetString("Q11QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q12.
        /// </summary>
        public static string Q12CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q12CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 12: Single Answer.
        /// </summary>
        public static string Q12QText {
            get {
                return ResourceManager.GetString("Q12QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q13.
        /// </summary>
        public static string Q13CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q13CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 13: Text.
        /// </summary>
        public static string Q13QText {
            get {
                return ResourceManager.GetString("Q13QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q14.
        /// </summary>
        public static string Q14CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q14CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 14: Single Answer.
        /// </summary>
        public static string Q14QText {
            get {
                return ResourceManager.GetString("Q14QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q15.
        /// </summary>
        public static string Q15CurrQCodeDesc {
            get {
                return ResourceManager.GetString("Q15CurrQCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question 15: Text.
        /// </summary>
        public static string Q15QText {
            get {
                return ResourceManager.GetString("Q15QText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string RightBtnLblNext {
            get {
                return ResourceManager.GetString("RightBtnLblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string RightBtnLblReview {
            get {
                return ResourceManager.GetString("RightBtnLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Survey.
        /// </summary>
        public static string SaveSurveyBtnLbl {
            get {
                return ResourceManager.GetString("SaveSurveyBtnLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Survey.
        /// </summary>
        public static string ScreenNameLblEndOfSurvey {
            get {
                return ResourceManager.GetString("ScreenNameLblEndOfSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string ScreenNameLblReview {
            get {
                return ResourceManager.GetString("ScreenNameLblReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Survey App.
        /// </summary>
        public static string ScreenNameLblStart {
            get {
                return ResourceManager.GetString("ScreenNameLblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Survey.
        /// </summary>
        public static string StartSurveyLbl {
            get {
                return ResourceManager.GetString("StartSurveyLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum character allowed is.
        /// </summary>
        public static string TextInstructionLbl {
            get {
                return ResourceManager.GetString("TextInstructionLbl", resourceCulture);
            }
        }
    }
}
